# Generated by Django 3.1.4 on 2020-12-13 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPLAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Higher_authority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='image',
            field=models.ImageField(upload_to='uploads/players/'),
        ),
    ]
