# Generated by Django 3.1.4 on 2020-12-13 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IPLAPP', '0003_scouting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teststat',
            fields=[

                ('id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='IPLAPP.player',primary_key=True)),
            ],
        ),
    ]
