# Generated by Django 3.1.4 on 2020-12-13 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IPLAPP', '0004_teststat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Odistat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odi_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='IPLAPP.player')),
            ],
        ),
    ]
