# Generated by Django 3.1.4 on 2020-12-13 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IPLAPP', '0005_odistat'),
    ]

    operations = [
        migrations.CreateModel(
            name='T20Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t20_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='IPLAPP.player')),
            ],
        ),
    ]
