# Generated by Django 3.1.4 on 2020-12-13 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IPLAPP', '0008_auto_20201214_0016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='odistat',
            old_name='odi_id',
            new_name='odi',
        ),
        migrations.RenameField(
            model_name='t20stat',
            old_name='t20_id',
            new_name='t20',
        ),
        migrations.RenameField(
            model_name='teststat',
            old_name='test_id',
            new_name='test',
        ),
    ]
