# Generated by Django 3.1.4 on 2020-12-13 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPLAPP', '0009_auto_20201214_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='baseprice',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='country',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='shortlisted',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='state',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
