# Generated by Django 3.1.4 on 2020-12-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPLAPP', '0011_auto_20201214_0115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='Player_id',
        ),
        migrations.AddField(
            model_name='player',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
