# Generated by Django 3.1.4 on 2020-12-14 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPLAPP', '0018_auto_20201214_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='T20STATI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField(default=0)),
            ],
        ),
    ]
