# Generated by Django 3.1.4 on 2020-12-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPLAPP', '0019_t20stati'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teststat',
            name='test',
        ),
        migrations.AddField(
            model_name='teststat',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
